// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCC-GKFcugyJInOFKRAA78rtJcUT7cbJE',
    appId: '1:160425566466:web:525a38d5d09a77c414621b',
    messagingSenderId: '160425566466',
    projectId: 'esp32-f9373',
    authDomain: 'esp32-f9373.firebaseapp.com',
    databaseURL: 'https://esp32-f9373-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-f9373.appspot.com',
    measurementId: 'G-77XS254MM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUG_gm_uid_QrT7yoaHC3ZTZnW5QgTuFI',
    appId: '1:160425566466:android:2ee4b49687699aaf14621b',
    messagingSenderId: '160425566466',
    projectId: 'esp32-f9373',
    databaseURL: 'https://esp32-f9373-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-f9373.appspot.com',
  );

}