// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDD6f93Q_LkBNvaoMbOamFLsODOG4-FGk',
    appId: '1:722724215256:web:0dd8a92f27c6ed78d0baad',
    messagingSenderId: '722724215256',
    projectId: 'prueba-8a3b1',
    authDomain: 'prueba-8a3b1.firebaseapp.com',
    databaseURL: 'https://prueba-8a3b1-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-8a3b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5uuJzgufJYKIqvdVlwbqO8kOkif4U9I',
    appId: '1:722724215256:android:26258d2facc66fb0d0baad',
    messagingSenderId: '722724215256',
    projectId: 'prueba-8a3b1',
    databaseURL: 'https://prueba-8a3b1-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-8a3b1.appspot.com',
  );
}
